var ItemType;
(function (ItemType) {
    ItemType[ItemType["TYPE_0"] = 0] = "TYPE_0";
    ItemType[ItemType["TYPE_1"] = 1] = "TYPE_1";
    ItemType[ItemType["TYPE_2"] = 2] = "TYPE_2";
    ItemType[ItemType["TYPE_3"] = 3] = "TYPE_3";
    ItemType[ItemType["TYPE_4"] = 4] = "TYPE_4";
    ItemType[ItemType["TYPE_5"] = 5] = "TYPE_5";
    ItemType[ItemType["TYPE_6"] = 6] = "TYPE_6";
    ItemType[ItemType["TYPE_7"] = 7] = "TYPE_7";
    ItemType[ItemType["TYPE_8"] = 8] = "TYPE_8";
    ItemType[ItemType["TYPE_9"] = 9] = "TYPE_9";
    ItemType[ItemType["TYPE_10"] = 10] = "TYPE_10";
    ItemType[ItemType["TYPE_11"] = 11] = "TYPE_11";
    ItemType[ItemType["TYPE_12"] = 12] = "TYPE_12";
    ItemType[ItemType["TYPE_13"] = 13] = "TYPE_13";
    ItemType[ItemType["TYPE_14"] = 14] = "TYPE_14";
    ItemType[ItemType["TYPE_15"] = 15] = "TYPE_15";
    ItemType[ItemType["TYPE_16"] = 16] = "TYPE_16";
    ItemType[ItemType["TYPE_17"] = 17] = "TYPE_17";
    ItemType[ItemType["TYPE_18"] = 18] = "TYPE_18";
    ItemType[ItemType["TYPE_19"] = 19] = "TYPE_19";
    ItemType[ItemType["TYPE_20"] = 20] = "TYPE_20";
    ItemType[ItemType["TYPE_21"] = 21] = "TYPE_21";
    ItemType[ItemType["TYPE_22"] = 22] = "TYPE_22";
    ItemType[ItemType["TYPE_23"] = 23] = "TYPE_23";
    ItemType[ItemType["TYPE_24"] = 24] = "TYPE_24";
    ItemType[ItemType["TYPE_25"] = 25] = "TYPE_25";
})(ItemType || (ItemType = {}));
//# sourceMappingURL=ItemType.js.map